version: '3'

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    image: news-blog
    ports:
      - "3000:3000"
    env_file: .env
    container_name: news-blog-web
